### ISSUE TITLE
__main__ and modularity implementation

### ISSUE THREAD

**Issue by mebaysan** [mehmetbuyukgumus/2022-2027-French-Deputies-List#3]
Hi @mehmetbuyukgumus 

You can make the code modular to improve readabilty. You can define functions to parse HTML elements etc. You just need to think about on how will you organize your code!

Also, you can implement a `main` function/method to your program. You can check [here](https://realpython.com/python-main-function/) to learn about it...

Regards!

**Comment by mehmetbuyukgumus** [comment]
Closed at new branch
